- name: Log in to quay.io
  shell: docker login --email=ops@ripple.com --username={{webapp_docker_username}} --password={{webapp_docker_password}} quay.io
- name: Pull docker image
  shell: docker pull quay.io/ripple/validators.ripple.com:{{deploy_environment}}
- name: Log out of quay.io
  shell: docker logout quay.io
- name: Stand up webapp container
  docker:
    name: validatorsripplecom_web
    image: "quay.io/ripple/validators.ripple.com:{{deploy_environment}}"
    state: reloaded
    restart_policy: always
    expose:
      - 1337
    env:
      DATABASE_URL: "{{webapp_database_url}}"
      PEERS_API_URL: "{{ lookup('env','PEERS_API_URL') }}"
      BASIC_AUTH_USER: "{{webapp_submit_username}}"
      BASIC_AUTH_PASS: "{{webapp_submit_password}}"
      NODE_ENV: production
