- name: Pull docker image
  shell: docker pull gliderlabs/logspout
- name: Stand up logspout
  docker:
    name: logspout
    state: reloaded
    privileged: true
    image: "gliderlabs/logspout"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: "{{logspout_uri}}"
